### ISSUE TITLE
ERROR: Uncaught exception: java.lang.IllegalArgumentException: Incorrect nucleotide char: "Y"

### ISSUE THREAD

**Issue by quyho0944** [ctlab/metacherchant#14]
metacherchant.sh --tool environment-finder \
                --k 31 \
                --coverage=5 \
                --reads ../data/testOutput.fastq \
                --seq /dataAndScripts/ARG.fasta \
                --maxradius 2000 \
                --output ../data/output \
                --work-dir ../data/output/metacherchant_logs \
                --maxkmers=100000 \
                --bothdirs=False \
                --chunklength=250 \
                -m 5G
this is the code i runned but  it have an error like this :
10-Apr-24  16:29:25  MAIN: Running tool environment-finder
10-Apr-24  16:29:25  |   Loading file testOutput.fastq...
10-Apr-24  16:29:26  |   1'041 reads added
10-Apr-24  16:29:26  Hashtable size: 105157 kmers
10-Apr-24  16:29:26  ERROR: Uncaught exception: java.lang.IllegalArgumentException: Incorrect nucleotide char: "Y"
java.lang.IllegalArgumentException: Incorrect nucleotide char: "Y"
	at ru.ifmo.genetics.dna.DnaTools.fromChar(DnaTools.java:59)
	at ru.ifmo.genetics.dna.DnaQ.<init>(DnaQ.java:27)
	at ru.ifmo.genetics.utils.iterators.DnaQIteratorFromDnaIterator.next(DnaQIteratorFromDnaIterator.java:21)
	at ru.ifmo.genetics.utils.iterators.DnaQIteratorFromDnaIterator.next(DnaQIteratorFromDnaIterator.java:5)
	at ru.ifmo.genetics.io.ReadersUtils.loadDnaQs(ReadersUtils.java:205)
	at tools.EnvironmentFinderMain.loadInput(EnvironmentFinderMain.java:117)
	at tools.EnvironmentFinderMain.runImpl(EnvironmentFinderMain.java:156)
	at ru.ifmo.genetics.utils.tool.Tool.simpleRun(Tool.java:287)
	at ru.ifmo.genetics.utils.tool.Tool.runAsStep(Tool.java:371)
	at ru.ifmo.genetics.utils.tool.Tool.run(Tool.java:451)
	at ru.ifmo.genetics.utils.tool.Tool.mainImpl(Tool.java:607)
	at ru.ifmo.genetics.Runner.run(Runner.java:176)
	at Runner.main(Runner.java:59)
and i don't know how to fix it , look line the error in nucleotide char in --reads ../data/testOutput.fastq  but when i try to check it sequence by using this code
cat ../data/testOutput.fastq  | awk 'NR%4==2{print}' | grep -oP "[^ATCG]"
the only char is ATGC
if you have any solution for this type of error please let me know it, it will help me a lot in my project

**Comment by ivartb** [comment]
Hello!
Probably the error is with nucleotide in `--seq /dataAndScripts/ARG.fasta` file. Can you please check it the same way you described?

Kind regards,
Artem

**Comment by quyho0944** [comment]
than you a lot sir, now it work but when i run ./metacherchant.sh  in my folder it seem not work but when i try to export it to $PATH 
metacherchant.sh is work .
```
./metacherchant.sh 
Error: Invalid or corrupt jarfile ./metacherchant.sh
```
```
metacherchant.sh
/home/hp/mambaforge/bin/metacherchant.sh: line 23: let: mem=: syntax error: operand expected (error token is "=")
/home/hp/mambaforge/bin/metacherchant.sh: line 24: * 95 / 100: syntax error: operand expected (error token is "* 95 / 100")
MetaCherchant: genomic environment analysis tool, version 0.1.0 (revision 329e235)

Usage:     metacherchant [<Launch options>] [<Input parameters>]
Tool:           environment-finder
Description:    Finds graphic environment for many genomic sequences in given metagenomic reads
Input parameters (only important):
	-k, --k <arg>                           k-mer size (MANDATORY)
	--seq <arg>                             FASTA file with sequences (MANDATORY)
	-o, --output <arg>                      output directory (MANDATORY)

Launch options (only important):
	-m, --memory <arg>                      memory to use (for example: 1500M, 4G, etc.) (optional, default: 2 Gb)
	-w, --work-dir <arg>                    working directory (optional, default: workDir)
	-c, --continue                          continue the previous run from last succeed stage, saved in working directory (optional)
	--force                                 force run with rewriting old results (optional)
	-h, --help                              print short help message (optional)

```
so how to fix this error?

**Comment by ivartb** [comment]
To get rid of this error, you have to set the mandatory parameters, such as `--k`, `--seq`, and `--output`. Alternatively, you can set `-h` parameter to see help message. Bash script doesn't seem to work well without input parameters.
